export const projects = [
  {
    name: "Davi Andrade",
    description: "Portfólio pessoal.",
    screenshot: "/images/portfolio.webp",
    alt: "Página inicial do portfólio com navbar, texto de apresentação e links de redirecionamento.",
    repositoryUrl: "https://github.com/davi-andrade-js/dv-portfolio",
    liveUrl: "",
    technologies: [
      "TypeScript",
      "React",
      "Next.js",
      "Tailwind CSS",
      "Shadcn/ui",
    ],
    year: "2024",
  },
  {
    name: "Thinker AI",
    description:
      "Ferramenta de IA com geração de textos, imagens, vídeos, áudio e código.",
    screenshot: "/images/thinker.webp",
    alt: "Dashboard com navbar e opções de geração.",
    repositoryUrl: "https://github.com/davi-andrade-js/Thinker-AI",
    liveUrl: "https://thinker-pmm0suqah-davis-projects-820de78a.vercel.app/",
    technologies: [
      "TypeScript",
      "React",
      "Next.js",
      "Tailwind CSS",
      "Shadcn/ui",
      "OpenAI API",
      "Replicate API",
    ],
    year: "2024",
  },
  {
    name: "Player de Música Retrô",
    description: "Player de música inspirado no visual do Windows 95.",
    screenshot: "/images/music-player.webp",
    alt: "Tela inicial com o modal do player de música aberto.",
    repositoryUrl: "https://github.com/davi-andrade-js/Retro-Music-Player",
    liveUrl: "https://davi-andrade-js.github.io/Retro-Music-Player/",
    technologies: ["JavaScript", "HTML", "CSS"],
    year: "2023",
  },
  {
    name: "Calc.js",
    description: "Simples calculadora.",
    screenshot: "/images/calc.webp",
    alt: "Tela estática com a calculadora.",
    repositoryUrl: "https://github.com/davi-andrade-js/Calc.js",
    liveUrl: "https://davi-andrade-js.github.io/Calc.js/",
    technologies: ["JavaScript", "HTML", "CSS"],
    year: "2023",
  },
  {
    name: "Weather App",
    description: "Aplicação de clima e tempo com a API OpenWeather.",
    screenshot: "/images/weather.webp",
    repositoryUrl: "",
    liveUrl: "",
    technologies: [
      "TypeScript",
      "React",
      "Next.js",
      "Tailwind CSS",
      "OpenWeatherAPI",
    ],
    year: "2024",
  },
];
